name: 5月31日自动提醒
on:
  schedule:
    - cron: "0 23 30 5 *"
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    environment: 5月31日自动提醒
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run renewal script
        env:
          TIXINGYOUXIANG_SMTP_PASSWORD: ${{ secrets.TIXINGYOUXIANG_SMTP_PASSWORD }}
        run: python 5月31日自动提醒.py